services:
  postgresdb:
    build:
      context: ./postgresDB
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgressql/data
    container_name: postgres
  financefam:
    build:
      context: ./FinanceFamApp
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    container_name: financefam
  
volumes:
  pgdata:





